services:
  pulsexpress:
    image: laravel:latest
    container_name: laravel_app
    context: ./pulsexpressv2/
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: IamRoot
      MYSQL_DATABASE: pulsexpress
      MYSQL_USER: pulsexpress
      MYSQL_PASSWORD: pulsexpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data: